services:
  postgres:
    # Expose additional port for local development tools
    ports:
      - "5432:5432"
    environment:
      # Enable more verbose logging in development
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"

  redis:
    # Expose Redis port for local development tools
    ports:
      - "6379:6379"
    # Enable Redis CLI access in development
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --protected-mode no

  propel-dashboard-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_HTTP_PORTS=8080  # Container port
      - ASPNETCORE_HTTPS_PORTS=8081 # Container port (if HTTPS needed)
    ports:
      - "5038:8080"  # Host:Container mapping
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./dashboard-api:/app/source:ro
      - ./dashboard-api/appsettings.Development.json:/app/appsettings.Development.json:ro 

  propel-dashboard-website:
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5038/api
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=80
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    volumes:
      - ./dashboard-react:/app
      - /app/node_modules  # Anonymous volume to prevent overwriting node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]


